### ISSUE TITLE
Internal Syntax Error

### ISSUE THREAD

**Issue by supercoolspy** [dbeaver/dbeaver-jdbc-libsql#12]
I am trying to use the libsql driver for my minecraft server running java 21. Upon attempting to run this query
```kotlin
conn.prepareStatement("insert into practicedata (uuid, pitch, npc) values ?, ?, ?").use { prepStatement ->
                    prepStatement.setString(1, uuid.toString())
                    prepStatement.setString(2, "normal")
                    val registry = CitizensAPI.getNPCRegistry()
                    val method = Bukkit.getScheduler().callSyncMethod(
                        JavaPlugin.getPlugin(AutoPitch::class.java)
                    ) {
                        registry.createNPC(EntityType.PLAYER, "Pitcher") // Replace arg1, arg2 with the actual arguments
                    }
                    val id = method.get().id
                    prepStatement.setInt(3, id)
                    prepStatement.execute()

                    return PracticePlayer(
                        uuid,
                        "normal",
                        id
                    )
                }
```
I get the error:
```
[11:59:55 WARN]: java.sql.SQLException: Internal Error: `syntax error around L1:53: ```
[11:59:55 WARN]: 	at AutoPitch-1.0.jar//com.dbeaver.jdbc.driver.libsql.client.LibSqlClient.executeBatch(LibSqlClient.java:128)
[11:59:55 WARN]: 	at AutoPitch-1.0.jar//com.dbeaver.jdbc.driver.libsql.client.LibSqlClient.execute(LibSqlClient.java:84)
[11:59:55 WARN]: 	at AutoPitch-1.0.jar//com.dbeaver.jdbc.driver.libsql.LibSqlStatement.execute(LibSqlStatement.java:61)
[11:59:55 WARN]: 	at AutoPitch-1.0.jar//dev.cosmics.autopitch.object.PracticePlayer$Companion.init(PracticePlayer.kt:26)
[11:59:55 WARN]: 	at AutoPitch-1.0.jar//dev.cosmics.autopitch.PracticeManager.getPracticePlayerBypassCache(PracticeManager.kt:47)
[11:59:55 WARN]: 	at AutoPitch-1.0.jar//dev.cosmics.autopitch.PracticeManager.getPracticePlayer(PracticeManager.kt:32)
[11:59:55 WARN]: 	at AutoPitch-1.0.jar//dev.cosmics.autopitch.event.PlayerJoin.preJoin(PlayerJoin.kt:17)
[11:59:55 WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor82.execute(Unknown Source)
[11:59:55 WARN]: 	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
[11:59:55 WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77)
[11:59:55 WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[11:59:55 WARN]: 	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
[11:59:55 WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
[11:59:55 WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615)
[11:59:55 WARN]: 	at net.minecraft.server.network.LoginListener.callPlayerPreLoginEvents(LoginListener.java:320)
[11:59:55 WARN]: 	at net.minecraft.server.network.LoginListener$2.run(LoginListener.java:265)
[11:59:55 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[11:59:55 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[11:59:55 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
[11:59:55 ERROR]: Could not pass event AsyncPlayerPreLoginEvent to AutoPitch v1.0
java.sql.SQLException: Internal Error: `syntax error around L1:53: ```
	at com.dbeaver.jdbc.driver.libsql.client.LibSqlClient.executeBatch(LibSqlClient.java:128) ~[AutoPitch-1.0.jar:?]
	at com.dbeaver.jdbc.driver.libsql.client.LibSqlClient.execute(LibSqlClient.java:84) ~[AutoPitch-1.0.jar:?]
	at com.dbeaver.jdbc.driver.libsql.LibSqlStatement.execute(LibSqlStatement.java:61) ~[AutoPitch-1.0.jar:?]
	at dev.cosmics.autopitch.object.PracticePlayer$Companion.init(PracticePlayer.kt:26) ~[AutoPitch-1.0.jar:?]
	at dev.cosmics.autopitch.PracticeManager.getPracticePlayerBypassCache(PracticeManager.kt:47) ~[AutoPitch-1.0.jar:?]
	at dev.cosmics.autopitch.PracticeManager.getPracticePlayer(PracticeManager.kt:32) ~[AutoPitch-1.0.jar:?]
	at dev.cosmics.autopitch.event.PlayerJoin.preJoin(PlayerJoin.kt:17) ~[AutoPitch-1.0.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor82.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:git-Paper-499]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.4.jar:git-Paper-499]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.4.jar:git-Paper-499]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.callPlayerPreLoginEvents(ServerLoginPacketListenerImpl.java:320) ~[?:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl$2.run(ServerLoginPacketListenerImpl.java:265) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
```
I know this probably isn't enough to diagnose the issue so let me know if I need to provide any further details

**Comment by serge-rider** [comment]
Thanks for the report. Seems to be related to uuid/int parameter binding

**Comment by serge-rider** [comment]
In fact it is not a bug. You have an incorrect query. It has to be
```sql
insert into practicedata (uuid, pitch, npc) values (?, ?, ?)
```

**Comment by supercoolspy** [comment]
Yep, thank you!
