### ISSUE TITLE
Add transactions support

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver-jdbc-libsql#7]
We have to im[plement #6 first

**Comment by StefanOltmann** [comment]
I see, that's why it won't work with JetBrains Exposed.

```
java.sql.SQLFeatureNotSupportedException: null
	at com.dbeaver.jdbc.model.AbstractJdbcConnection.setTransactionIsolation(AbstractJdbcConnection.java:131)
	at org.jetbrains.exposed.v1.jdbc.statements.jdbc.JdbcConnectionImpl.setTransactionIsolation(JdbcConnectionImpl.kt:85)
```
